name: Renfe Ticket Monitor

on:
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

  schedule:
    # Ejecuta el script cada 15 minutos.
    # Puedes cambiarlo. "*/30" sería cada 30 min. "0 * * * *" sería cada hora.
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código de tu repositorio a la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta el script de Renfe
      - name: Run Renfe Scraper
        env:
          # Pasa los secretos de GitHub como variables de entorno al script
          EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
          EMAIL_CONTRASENA_APP: ${{ secrets.EMAIL_CONTRASENA_APP }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: |
          # El script ya está configurado para ejecutarse en modo headless
          python renfe_scraper.py
